apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb-default
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true" # use this as default class
spec:
  controller: ingress.k8s.aws/alb # use application lb