apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
  tolerations: #kubectl taint nodes node1 app=web:NoSchedule would be the taint
    - key: app
      operator: Equal
      value: web
      effect: NoSchedule