apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
  - name: my-container
    image: my-image:latest
    # Mount ConfigMap as a file
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    # Reference ConfigMap values as environment variables
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: database-url
    - name: FILE_PATH
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: file-path
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap
      items:
      - key: app-config.json
        path: myfile.json  # Mount as /etc/config/myfile.json
