kubectl config set-cluster kubernetes \
  --certificate-authority=/etc/kubernetes/pki/ca.crt \
  --embed-certs=true \
  --server=https://<api-server-endpoint> \
  --kubeconfig=scheduler-kubeconfig.yaml

kubectl config set-credentials scheduler \
  --client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt \
  --client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key \
  --embed-certs=true \
  --kubeconfig=scheduler-kubeconfig.yaml

kubectl config set-context default \
  --cluster=kubernetes \
  --user=scheduler \
  --kubeconfig=scheduler-kubeconfig.yaml

kubectl config use-context default --kubeconfig=scheduler-kubeconfig.yaml
