apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler
  namespace: kube-system
spec:
  containers:
  - name: custom-scheduler
    image: k8s.gcr.io/kube-scheduler:v1.30.0 # or your desired version
    command:
    - kube-scheduler
    - --config=/etc/kubernetes/scheduler-config.yaml
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: kubernetes-config
      readOnly: true
  volumes:
  - name: kubernetes-config
    hostPath:
      path: /etc/kubernetes
