apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota      # Name of the ResourceQuota object
  namespace: your-namespace    # Namespace in which this ResourceQuota is applied
spec:
  hard:
    requests.cpu: "4"           # Maximum CPU resources that can be requested in the namespace (4 CPUs)
    requests.memory: "8Gi"      # Maximum memory that can be requested in the namespace (8 GiB)
    limits.cpu: "10"            # Maximum CPU limits in the namespace (10 CPUs)
    limits.memory: "16Gi"       # Maximum memory limits in the namespace (16 GiB)
    pods: "10"                  # Maximum number of Pods that can be created in the namespace (10 Pods)
    services: "5"               # Maximum number of Services that can be created in the namespace (5 Services)
    persistentvolumeclaims: "3" # Maximum number of PersistentVolumeClaims that can be created (3 PVCs)
    configmaps: "5"             # Maximum number of ConfigMaps (5 ConfigMaps)
    secrets: "10"               # Maximum number of Secrets (10 Secrets)
