apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: kube-test
spec:
  limits:
    - default:
        memory: "512Mi" # if container do not specific its on  limit on memory use this
        cpu: "500m"  # if container do not specific its on  limit on cpu use this
      defaultRequest:
        memory: "256Mi" # if container do not specific its on  request on memory use this
        cpu: "300m" # if container do not specific its on  limit on cpu use this
      type: Container