apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  # Pod-level security context
  securityContext:
    runAsUser: 1000                # Run all containers as UID 1000
    runAsGroup: 3000              # Primary GID for the containers
    fsGroup: 2000                 # Group ID for mounted volumes
  containers:
  - name: secure-app
    image: nginx:stable
    ports:
      - containerPort: 80
    # Container-level security context
    securityContext:
      allowPrivilegeEscalation: false     # Prevent privilege escalation
      readOnlyRootFilesystem: true        # Root FS is read-only
      privileged: false                   # Container is NOT privileged
      capabilities:
        drop:
          - ALL                           # Drop all Linux capabilities
        add:
          - NET_BIND_SERVICE              # (Optional) Allow binding to low ports
